stages:
  data_ingestion:
    cmd: python src/pipeline/Stage_01_dataingestion.py
    deps:
      - src/pipeline/Stage_01_dataingestion.py
      - config/config.yaml

    outs:
      - artifacts/data_ingestion

  transformed_data:
    cmd: python src/pipeline/Stage_02_transform_data.py

    deps: 
      - src/pipeline/Stage_02_transform_data.py

    outs:
      - artifacts/transformed_data

  prepare_model:
    cmd: python src/pipeline/stage_03_model_trainer.py

    deps: 
      -  src/pipeline/stage_03_model_trainer.py


  evaluation:
    cmd: python src/pipeline/Stage_04_model_evaluation.py
    deps:
      - src/pipeline/Stage_04_model_evaluation.py